FROM node:20

# Set work directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install

# Copy project
COPY . .

# Build the application
RUN npm run build

# Serve the application
CMD ["npx", "serve", "-s", "build"]

# Expose the port the app runs on
EXPOSE 3000
